### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tjbenton** [darcyclarke/DSS#52]
This seems like a really useful tool but the docs could use an update. With more complete examples starting from the beginning not from the end. I like DSS over the other generators because it allows you to use scss comments.

In your only example on how to use DSS you just have this
```
var lines = fs.readFileSync('styles.css'),
    options = {},
    callback = function(parsed){
      console.log(parsed);
    };
dss.parse(lines, options, callback);
```

I'm assuming `fs` is a node package, and when I looked into it [here](https://www.npmjs.org/package/fs) it says that this package has been *unpublished*. Also I have no idea the context of where to put this code at to get this to work. 
I'm currently using [gulp](http://gulpjs.com/) as my task runner because it's not as bloated as grunt. There is a [gulp-dss](https://www.npmjs.org/package/gulp-dss) package available but the documentation there is sub par. There are only 2 options, and neither of them are to add a custom parser.

**Comment by tbleckert** [comment]
fs is a native node package https://nodejs.org/api/fs.html#fs_file_system

**Comment by darcyclarke** [comment]
This should be updated in the [Readme](https://github.com/darcyclarke/DSS) now. Apologize that it was even more vague before. Better documentation is on it's way.
