### ISSUE TITLE
Parsing multiple files at once in nested directories doesn't work

### ISSUE THREAD

**Issue by reintroducing** [darcyclarke/DSS#60]
Hello,
I'm trying to use DSS to parse a directory of Sass files that has nested directories and files within those directories.  To do this I've written a task using glob and read-multiple-files which works perfectly as long as the files are in the main sass directory.  I've uploaded a zip file to demonstrate this: http://dev.reintroducing.com/2015/dss.zip

If you unzip that and run `node index.js` from the command line in the directory you'll see that the generated dss.json file doesn't have the comment from the file in `sass/common/_breadcrumbs.scss`.  Now move the breadcrumbs file into the same directory as _buttons.scss and run the command again and you will see that it's being generated properly.

Inside of index.js and in the glob portion if you log the files param you'll see in both cases the files are correct, in both cases the contents inside of readMultipleFiles are correct, yet the parsed file just has an empty "blocks" array unless the files are on the same level.  Obviously this is not desired as seldom do Sass files live in the same directory at all times.

Could you please take a few minutes and look at the files to see what I'm doing wrong?  Is this not a good way to utilize DSS?  If not, what is the best way to run DSS to parse a directory of Sass files which are nested in other directories?  The example in the readme doesn't demonstrate this rather an example of running it on a single file.

Thank you very much for your hard work on this wonderful tool.  Please let me know if there is anything else you need from me to try and help troubleshoot this.

**Comment by reintroducing** [comment]
I should also clarify that I'm running this as part of a gulp build so grunt-dss is not really an option as I'd rather not introduce grunt into the fold.

**Comment by reintroducing** [comment]
Apologies, I don't mean to spam this thread, but I have a few other findings that seem rather peculiar.

NOTE: At this point I've added a comment block above the `a

If you move _buttons.scss into the common folder and run the command again you only get the output from _breadcrumbs.scss in the "blocks" array. Strange as now it's reading the sub directories but only executing one file.

Same thing if you completely delete _buttons.scss from the file system, then it runs _breadcrumbs.scss fine as well.

**Comment by jeffjewiss** [comment]
Hi there, no worries about all of the messages.

I think I've figured out your issue. Currently DSS only supports strings with newlines to be parsed. However, the module `read-multple-files` that you're using returns a buffer.

So, if you update your `readMultipleFiles` function to:

```javascript
readMultipleFiles(files, function(err, contents) {
    if (err) {
        return console.log(err);
    }

    var css = contents.map(function(buffer) {
        return buffer.toString('utf-8');
    }).join('\n');

    dss.parse(css, null, function(parsed) {
````

You should be good to go. I was able to use the above and get an output in `dss.json` for your breadcrumbs.

**Comment by reintroducing** [comment]
That worked perfectly. Thank you for helping out, really appreciated.

**Comment by jeffjewiss** [comment]
You're welcome, I'm glad that solved the issue!
