### ISSUE TITLE
@markup is rendered sometimes ion top of the rendered markup and html code

### ISSUE THREAD

**Issue by DanielaValero** [darcyclarke/DSS#61]
Hello,

While using DSS in our project we noticed that sometimes @markup is rendered on top of the code example and the rendered markup, this is being caused because this comparison:

```javascript
  if (line && line != '@markup')
```
Is not strong enough for strings comparison.

The fix is to change it to:

```javascript
 if (line && && line.indexOf('@markup') == -1)
```

For which a pull request is being made: https://github.com/darcyclarke/DSS/pull/62

**Comment by darcyclarke** [comment]
@DanielaValero thanks for creating the pull request. It's now been fixed/update in https://github.com/darcyclarke/DSS/commit/47bcee4a3d54c59702aa58006ea26b351bac6660
